export const GET_EMPLOYEE_DATA = 'GET_EMPLOYEE_DATA';
export const GET_EMPLOYEE_SPORT_DATA = 'GET_EMPLOYEE_SPORT_DATA';
export const CLEAR_EMPLOYEE_DETAILS = 'CLEAR_EMPLOYEE_DETAILS';
export const GET_EMPLOYEE_OFFERS_DATA = 'GET_EMPLOYEE_OFFERS_DATA';